### ISSUE TITLE
notebook file path not found

### ISSUE THREAD

**Issue by JeanBilheux** [jhamrick/nbflow#4]
I have been trying to run the examples (from this repo and also from the following repo https://github.com/jhamrick/nbflow-example) with both the same result at the end. **scons** commands fails as the program tries to look for a *funny* notebook path name. I checked that I was at the right place when running both cases.

Terminal output

(scons) mac95470:example j35$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
analyses/gen_data.ipynb --> results/data.json
Traceback (most recent call last):
  File "/Users/j35/anaconda/envs/scons/bin/jupyter-nbconvert", line 6, in <module>
    main()
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 429, in convert_single_notebook
    write_results = self.write_single_notebook(output, resources)
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 390, in write_single_notebook
    output, resources, notebook_name=notebook_name)
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbconvert/writers/files.py", line 127, in write
    with io.open(dest, 'w', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: 'analyses/analyses/gen_data.ipynb'
scons: *** [results/data.json] RuntimeError : Error executing notebook
Traceback (most recent call last):
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/scons-2.5.0/SCons/Action.py", line 1054, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/Users/j35/anaconda/envs/scons/lib/python2.7/site-packages/nbflow/scons.py", line 20, in build_notebook
    raise RuntimeError("Error executing notebook")
RuntimeError: Error executing notebook
scons: building terminated because of errors.

<<
the following error line is what puzzles me.
IOError: [Errno 2] No such file or directory: 'analyses/analyses/gen_data.ipynb'
>>

**Comment by camillescott** [comment]
Just dealt with this myself - it results from the nbconvert command using both `--inplace` and specifying itself as an output. Can put up a PR shortly!

**Comment by jhamrick** [comment]
Fixed by #6 

Thanks @camillescott !

Try updating your install @JeanBilheux and see if that works for you.

**Comment by JeanBilheux** [comment]
Good job. Works perfectly for me now. Thank you.
